Sprint 4
SergeyKorevskiy/MovieQuiz-ios pull request #2
Opened 2023-03-04 22:11 UTC by SergeyKorevskiy

Почти весь проект 4-го спринта делал в первоначальной ветке project_sprint_3_start, сдалал форк sprint_4 уже в конце. И тут началась проблема: шрифты YS Display пропали и видно их было только только в варианте Atributed, а не в варианте Plain -> Custom. Удалил всю инфо по шрифтам, все папки, ссылки и заново их установил с парой перезагрузок. Но так ничего и не изменилось. При этом если открывать ветку project_sprint_3_start то все прекрасно работает. В итоге думаю причина была в том что после форка новый экземпляр проекта сохранился в папке Документы ((/Users/пользователь/Documents). И после того как я перенес его на iCloud, в "соседнюю" папку с проектом предыдущей ветки, то сразу все заработало. Какая связь конечно не понятно, может вы подскажите?

И второй вопрос. В такой аварийной ситуации один из кураторов предложил вписывать шрифты вручную кодом, вот в такой нотации label.font = UIFont(name: "YSDisplay-Bold", size: 10). Логично предположить что вместо "label" используем например ту самую переменную "textLabel" которую мы создаем в аутлете. А что делать с объектами (те ми же самыми Label например), с которыми нет аутлетов, а их параметры мы просто задаем в инспекторе Атрибутов? Что делать чтобы прописать их шрифт и его размер в самом коде? Создать для них аутлет, в котором будет просто всегда статичное значение?

2023-03-05 13:55 UTC, protos17 commented
Какая связь при переносе не могу сказать точно, бывают разные причины, самая популярная при переносе папок из проекта в проект или отсутствие файлов в BuildPhases. А для установки шрифта кодом, нужно вывести IBOutlet

2023-03-05 14:16 UTC, protos17 requested changes

2023-03-05 14:16 UTC, protos17 commented on MovieQuiz/AppDelegate.swift
> +     // sleep(3)
Рекомендую не оставлять лишний код, а удалить его, вместе с print выше

2023-03-05 14:16 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +  // Авторское решение:
Лишние комментарии рекомендую удалить из проекта

2023-03-05 14:16 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +  //textLabel.font = UIFont(name: "YSDisplay-Bold", size: 150)
Лишний закомментированный код рекомендую удалить. Для того, чтобы добавить шрифт кодом, нужно данную строку писать во viewDidLoad

2023-03-05 14:16 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +              text: "Рейтинг этого фильма больше чем 6?",
Повторяющуюся строчку рекомендую выносить в отдельную константу и обращаться к ней

2023-03-05 14:16 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +
Лишние отступы рекомендую удалять. Здесь же нужно задавать шрифты

2023-03-05 14:16 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +   }
Лишние неиспользуемые методы жизненного цикла viewControllera рекомендую удалить

2023-03-05 14:16 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
>  /*
Неиспользуемые мок-данные тоже рекомендую удалить

2023-03-05 14:16 UTC, protos17 commented on MovieQuiz/Presentation/en.lproj/Main.strings
> +/* Class = "UIButton"; normalTitle = "Да"; ObjectID = "d29-Ak-Haf"; */
Данный файл не добавлен в BuildPhases

2023-03-05 14:16 UTC, protos17 commented on MovieQuiz/Resources/Base.lproj/LaunchScreen.storyboard
>  </document>
Шрифты добавлены два раза - один раз в папке Fonts, второй раз в папке Fonts/YS Display

2023-03-05 16:32 UTC, SergeyKorevskiy commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +
Сделано.

2023-03-05 16:32 UTC, SergeyKorevskiy commented on MovieQuiz/AppDelegate.swift
> +     // sleep(3)
Сделано.

2023-03-05 16:32 UTC, SergeyKorevskiy commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +  // Авторское решение:
Сделано.

2023-03-05 16:32 UTC, SergeyKorevskiy commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +  //textLabel.font = UIFont(name: "YSDisplay-Bold", size: 150)
Готово. Спасибо.

2023-03-05 16:32 UTC, SergeyKorevskiy commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +              text: "Рейтинг этого фильма больше чем 6?",
Сделано.

2023-03-05 16:32 UTC, SergeyKorevskiy commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +   }
Сделано.

2023-03-05 16:32 UTC, SergeyKorevskiy commented on MovieQuiz/Presentation/MovieQuizViewController.swift
>  /*
Сделано.

2023-03-05 16:35 UTC, SergeyKorevskiy commented on MovieQuiz/Presentation/en.lproj/Main.strings
> +/* Class = "UIButton"; normalTitle = "Да"; ObjectID = "d29-Ak-Haf"; */
Из за того что случайно после того как была ситуация с попаданием кастомных шрифтов, я во время экспериментов поставил галку на "Localisation", хотя и сразу ее снял, английский все равно сохраняется. Скорее всего причина в этом. С помощью наставника объединили языки.

2023-03-05 16:35 UTC, SergeyKorevskiy commented on MovieQuiz/Resources/Base.lproj/LaunchScreen.storyboard
>  </document>
Из за того что случайно после того как была ситуация с попаданием кастомных шрифтов, я во время экспериментов поставил галку на "Localisation", хотя и сразу ее снял, английский все равно сохраняется. Скорее всего причина в этом. С помощью наставника объединили языки.

2023-03-05 16:37 UTC, SergeyKorevskiy commented
@protos17 Прошу принять мои исправления.

2023-03-16 16:14 UTC, protos17 approved these changes

2023-03-16 16:14 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +  static let quizQuestion: String = "Рейтинг этого фильма больше чем 6?"
Здесь стоит добавить `private`
Необходимо указывать private  для того, чтобы спрятать детали реализации конкретной части функциональности, 
когда они используются только внутри области объявления.

2023-03-18 16:37 UTC, SergeyKorevskiy commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +  static let quizQuestion: String = "Рейтинг этого фильма больше чем 6?"
Исправлено

2023-03-18 16:50 UTC, merged